NPM := npm

.PHONY: setup run-dev lint lint-fix build test

setup:
	$(NPM) ci

run-dev:
	$(NPM) run dev

lint:
	$(NPM) run lint

lint-fix:
	$(NPM) run lint:fix

build:
	$(NPM) run build

format:
	@echo "No formating implemented yet"

test:
	@echo "No tests implemented yet"
