---
name: ${APP_NAME}-compose

services:

# App
  frontend:
    container_name: ${APP_NAME}-fe
    image: ${FE_IMAGE}:${IMAGE_TAG}
    build:
      context: ../../app/frontend
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION}
        NEXT_PUBLIC_API_URL: http://localhost:${BE_PORT}
    ports:
      - ${FE_PORT}:3000
    depends_on:
      - backend

  backend:
    container_name: ${APP_NAME}-be
    image: ${BE_IMAGE}:${IMAGE_TAG}
    build:
      context: ../../app/backend
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION}
    environment:
      DB_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - ${BE_PORT}:8000
    depends_on:
      db:
        condition: service_healthy

# Infrastructure
  db:
    container_name: ${APP_NAME}-db
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  postgres_data:
