apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  POSTGRES_DB: {{ .Values.backend.database.name | quote }}
  POSTGRES_HOST: {{ .Values.backend.database.host | quote }}
  POSTGRES_PORT: {{ .Values.backend.database.port | quote }}